/*
 * Generated by erpcgen 1.7.4 on Wed Jul 29 15:58:40 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcCore0_server_h_)
#define _erpcCore0_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "erpcCore0.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10704 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for Core0.
 */
class Core0_service : public erpc::Service
{
public:
    Core0_service() : Service(kCore0_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for Core0_demoHello1 of Core0 interface. */
    erpc_status_t Core0_demoHello1_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Core0_demoHello2 of Core0 interface. */
    erpc_status_t Core0_demoHello2_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Core0_demoHello3 of Core0 interface. */
    erpc_status_t Core0_demoHello3_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "erpcCore0.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_Core0_service(void);

void destroy_Core0_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _erpcCore0_server_h_
