/*
 * Generated by erpcgen 1.7.4 on Wed Jul 29 16:11:36 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcCore1_server_h_)
#define _erpcCore1_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "erpcCore1.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10704 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for Core1.
 */
class Core1_service : public erpc::Service
{
public:
    Core1_service() : Service(kCore1_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for Core1_demoHello1 of Core1 interface. */
    erpc_status_t Core1_demoHello1_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Core1_demoHello2 of Core1 interface. */
    erpc_status_t Core1_demoHello2_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Core1_demoHello3 of Core1 interface. */
    erpc_status_t Core1_demoHello3_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for callback of Core1 interface. */
    erpc_status_t callback_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "erpcCore1.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_Core1_service(void);

void destroy_Core1_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _erpcCore1_server_h_
