/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.7.4 on Wed Jul 29 15:07:49 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcdemo_server_h_)
#define _erpcdemo_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "erpcdemo.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10704 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for DEMO.
 */
class DEMO_service : public erpc::Service
{
public:
    DEMO_service() : Service(kDEMO_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for RD_demoHello of DEMO interface. */
    erpc_status_t RD_demoHello_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RD_demoHello2 of DEMO interface. */
    erpc_status_t RD_demoHello2_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RD_demoHello3 of DEMO interface. */
    erpc_status_t RD_demoHello3_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

/*!
 * @brief Service subclass for Core0Interface.
 */
class Core0Interface_service : public erpc::Service
{
public:
    Core0Interface_service() : Service(kCore0Interface_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for myFun of Core0Interface interface. */
    erpc_status_t myFun_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for callback1 of Core0Interface interface. */
    erpc_status_t callback1_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "erpcdemo.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_DEMO_service(void);

void destroy_DEMO_service(void);

erpc_service_t create_Core0Interface_service(void);

void destroy_Core0Interface_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _erpcdemo_server_h_
